application: wakame-bot
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /statics
  static_dir: statics

- url: /.*
  script: application.view.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest